baseURL: "https://vaibhavkulkarni.bio/"
languageCode: "en-us"
title: "Vaibhav's Personal Website"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: tools
      name: Tools
      title: Free online tools
      url: /tools/
      weight: 2
    - identifier: resume
      name: Resume
      title: My Resume
      url: "/vaibhav_resume.pdf"
      weight: 3

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Vaibhav Kulkarni"
  description: Web developer and bioinformatics enthusiast
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/dna.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: false
    defaultTheme: "dark" # light

  font:
    fontSize: 1.5rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Vaibhav Kulkarni" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Vaibhav Kulkarni"
    subtitle: "A passionate web developer and bioinformatics enthusiast"
    content: "I have extensive experience in both research and programming, and I aim to combine my knowledge of science and technology to create impactful solutions."
    image: /images/me.png 
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/vaibhav_resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/vkulk094
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/vaibhav-kulkarni-bio/
        - icon: fab fa-instagram
          url: https://www.instagram.com/vaibhavkulkarn1/
#      customIcons:
#        - icon: /fav.png
#          url: "https://example.com"

  # About
  about:
    enable: true 
    title: "About Me"
    image: "/images/aboutme.png"
    content: |-
      I am Vaibhav Kulkarni.

      My experience spans across web development, bioinformatics pipelines, and data analysis, which allows me to contribute to both scientific research and modern web technologies.
      When I'm not coding or researching, you can find me exploring the latest in bioinformatics tools or contributing to open-source projects.
    skills:
      enable: true
      title: "Technologies and tools I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Node.js"
        - "Python"
        - "R"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Masters Research Student"
        company: "Masters"
        companyUrl: "https://www.uottawa.ca/"
        date: "Jan 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: Working as a graduate researcher for Dr. Stephane Aris-Brosou
        content: |
         Currently studying evolutionary relationships in viral species using bioinformatic approaches.
          - Developed custom bioinformatics scripts using Python,Bash and R to automate viral metagenome analysis.
          - Improved data processing efficiency by over 90% through the implementation of parallel processing based workflows.
          - Presented research findings at the Ottawa Carleton Biology Symposium with an attendance of 200+ people.

      - job: "Lab Demonstrator"
        company: "Lab Dem TA"
        companyUrl: "https://www.uottawa.ca/"
        date: "Jan 2023 - present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a lab demonstrator for Dr. Valerie Cardin & Dr. Gabriel Guillet.
        content: |
          Taught multiple lab sections for undergraduate courses like genetics, evolutionary biology and plant systematics. 
          - Responsible for grading quizzes,assignments and supervising students in laboratory settings.
          - Mentored and guided 50+ students in executing complex lab protocols.
          - Led a team of lab assistants in setting up experiments and maintaining safety standards.

      - job: "Honors Research Student"
        company: "Honors"
        companyUrl: "https://www.uottawa.ca/"
        date: "Sep 2022 - Apr 2023"
        info:
          enable: true
          content: I worked as an Honor's Research Student in Dr. Jan Mennigen's Lab
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Researched histone modifications in goldfish under chronic hypoxia, contributing to advancements in epigenetic research.
          - Developed new sample handling protocols to prevent contamination, improving experiment reproducibility by 25%.
          - Solved data inconsistencies by troubleshooting the sequencing pipeline, ensuring accurate results.

      - job: "Tutor"
        company: "Freelance"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a freelance tutor to support myself through university.
        content: |
          Developed and delivered personalized tutoring sessions for high school and college students in biology and chemistry.
          - **Customized Learning Plans**: Assessed individual learning styles and academic goals to create tailored educational plans that addressed cognitive diversity and improved engagement.
          - **Learning Outcome Optimization**: Boosted student performance by adapting instructional methods based on student progress, achieving measurable improvements in exam scores for 80% of students.
          - **Skill Development**: Mentored students to develop critical thinking, problem-solving skills, and subject mastery in preparation for standardized exams and college admissions.
          - **Feedback and Improvement**: Conducted regular assessments and provided detailed feedback to students and parents, adjusting study plans to continuously enhance learning outcomes.
          - **Use of Technology**: Incorporated digital tools like interactive simulations and virtual labs to make learning more engaging and accessible.

      - job: "Strength Statistics"
        company: "Miscellaneous"
        companyUrl: "https://example.com"
        date: "Sep 2019 - present"
        info:
          enable: true
          content: Some of my strength statistics on common powerlifting excercises (1RM).
        content: |
          - **Squat**: 113 kg (250 lbs) — Consistently working on improving leg strength, focusing on proper technique and controlled depth.
          - **Deadlift**: 129 kg (285 lbs) — Achieved personal bests through progressive overload training and technique refinement.
          - **Bench Press**: 75 kg (165 lbs) — Focused on increasing upper body strength and chest development with consistent training.
          - **Overhead Press**: 45 kg (100 lbs) — Continuously working on shoulder stability and pressing strength.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science in Biology (Bioinformatics)"
        school:
          name: "University of Ottawa"
          url: "https://www.uottawa.ca/"
        date: "2023 - 2025"
        content: |-
          Specializing in Bioinformatics with a focus on phylogenetic analysis and microbial research.
          - Researching microbial species diversity using bioinformatics tools and approaches.
          - Working on large-scale genomic data analysis to explore evolutionary patterns.
          - Actively involved in the Ottawa Carleton Biology Symposium, presenting research on geographical biases in viral databases.
      - title: "Bachelor of Science in Biology (Honors)"
        school:
          name: "University of Ottawa"
          url: "https://www.uottawa.ca/"
        date: "2019 - 2023"
        content: |-
          Graduated MAGNA CUM LAUDE with a specialization in Cellular and Molecular Biology.
          - Completed an honors thesis on the role of histone modifications in goldfish under chronic hypoxia.
          - Presented undergraduate research at departmental conferences, receiving recognition for contributions to epigenetics.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School Diploma (Science Stream)"
        school:
          name: "Jai Hind College"
          url: "https://www.jaihindcollege.com/index.html"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: "Dean's Honour List (Recognition of Excellence)"
        content: |
          Recognized for academic excellence through disciplined research and coursework at the University of Ottawa.
        date: "2021 - 2022"
        image: "/images/achievements/deans.webp"

      - title: "Ottawa Carleton Biology Symposium Presentation"
        content: |
          Presented research on mitigating geographical biases in viral reference databases, improving global data accuracy and representation.
        date: "April 2024"
        image: "/images/achievements/OCIB.webp"

      - title: "Graduate Representative - Equity, Diversity, and Inclusion Committee"
        content: |
          Elected as a graduate representative at the University of Ottawa to promote equitable academic policies and foster inclusivity.
        date: "2024 - 2025"
        image: "/images/achievements/edi.webp"

      - title: "Professional Development Officer - Biology Graduate Students' Association (BGSA)"
        content: |
          Elected as the Professional Development Officer for the BGSA, leading workshops on career planning and academic development for graduate students.
        date: "2024 - 2025"
        image: "/images/achievements/BGSA.jpg"
      
      - title: "Creator of Personal Website"
        content: |
          Developed and launched a personal website to showcase my portfolio, research, and blog content.
        date: "2024"
        image: "/images/achievements/webdev.webp"
        url: "https://vaibhavkulkarni.bio"

  # Projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: "Phylogenetic Analysis Pipeline"
        content: |
          Developed an automated bioinformatics pipeline for microbial sequence analysis, focusing on elucidating diversity.
        image: /images/projects/pipeline.webp
#        featured:
#          name: "View Project"
#          link: "https://github.com/vaibhavkulkarni/phylogenetic-pipeline"
        badges:
          - "Python"
          - "R"
          - "Bash"
        links:
          - icon: fab fa-github
            url: "https://github.com/vkulk094"

      - title: Personal Blog Website
        content: Designed, developed and deployed my own personal website to showcase my portfolio, research, and blog.
        image: /images/projects/website.webp
        featured:
          name: My Website
          link: https://vaibhavkulkarni.bio/
        badges:
          - "HTML"
          - "CSS"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/vkulk094/MyWebsite

      - title: Field Stations Mapping App
        content: |
          Developed a web app to map and display research field stations. The app helps track station locations, research data, and logistical information for Dr. Gabriel Guillet’s lab.
        image: /images/projects/mapsapp.png
        featured:
          name: "View Project"
          link: "https://vkulk094.github.io/FieldStationsMap2/"
        badges:
        - "JavaScript"
        - "Google Maps API"
        - "HTML"
        links:
        - icon: fab fa-github
          url: "https://github.com/vkulk094/FieldStationsMap2"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:vybavk@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/vkulk094
      linkedin: https://www.linkedin.com/in/vaibhav-kulkarni-bio/
      #twitter: https://twitter.com
      instagram: https://www.instagram.com/vaibhavkulkarn1/
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Vaibhav Kulkarni, All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
